### ISSUE TITLE
using host volumes/bindings leads to missing config

### ISSUE THREAD

**Issue by r2ixuz** [si458/zpush#1]
If you deploy the container for the first time with all three folders as local volumes binded, the files policies.ini and z-push.conf.php from etc/z-push folder are missing.

But anyways, nice dockerfile. Thanks for your work! :-)

**Comment by si458** [comment]
Thanks for the info,
I will investigate this unless you have a pull request for the fix

**Comment by r2ixuz** [comment]
Sorry no pull request. I guess you need to check if a config is already present at the binded etc/ volume or not. Don't know how to do this.

**Comment by r2ixuz** [comment]
Oops my fault, not only these two configs were missing. Every config file were missing under /etc/z-push/ .

**Comment by si458** [comment]
can you confirm whats the command or dockerfile or docker-compose you are using?
ive tried it here and no issues?
it creates the volumes automatically and then it has all the config files inside?
```
version: '2'
services:
  zpush: 
    image: si458/zpush:latest
    volumes:
      - logs:/var/log/z-push
      - config:/etc/z-push
      - data:/var/lib/z-push
    restart: always
    ports:
      - 8081:80
volumes:
  logs:
    driver: local
  config:
    driver: local
  data:
    driver: local
```

**Comment by r2ixuz** [comment]
Instead of local volumes, I use host volumes/binded volumes. My docker-compose this:

    version: '2'
    services:
      zpush: 
        image: si458/zpush:latest
        volumes:
          - /data/zpush/logs:/var/log/z-push
          - /data/zpush/config:/etc/z-push
          - /data/zpush/data:/var/lib/z-push
        restart: always
        ports:
          - 8081:80


With this, the configs are missing. If I use your docker-compose with local volumes. It works as intended.

**Comment by si458** [comment]
you are indeed correct!
i have always used volumes, never used binds before, 
so ill investigate it a bit more and come back once i work things out 👍

**Comment by si458** [comment]
Hi @r2ixuz 
forgive the long delay
i have re-done the dockerfile
can you try the build `si458/zpush:2.5.2` for me please? (new code in https://github.com/si458/zpush/tree/2.5.2) 
it now uses Debian buster-slim, PHP 7.3, supports all the backends inc kopano
and should also copy files at first run if they aren't present 👍
(will not copy files if folder/mount is readonly like in kubernetes configmaps)

you can use the following docker-compose.yml
```
version: '2'
services:
  zpush: 
    image: si458/zpush:2.5.2
    volumes:
      - logs:/var/log/z-push
      - config:/config
      - data:/var/lib/z-push
    restart: always
    ports:
        - 80
volumes:
  logs:
    driver: local
  config:
    driver: local
  data:
    driver: local
```

**Comment by Daniel15** [comment]
@si458  I had the same issue, and `si458/zpush:2.5.2` fixed it for me. Like @r2ixuz, I'm using binds rather than volumes:

```yaml
  zpush:
    container_name: zpush
    image: si458/zpush:2.5.2
    volumes:
      - /var/local/docker/zpush/logs:/var/log/z-push
      - /var/local/docker/zpush/config:/config
      - /var/local/docker/zpush/data:/var/lib/z-push
    restart: unless-stopped
```
